---
  - name: Load State for IPv6 Subnet
    include_vars:
      file: "{{ provisioner_state_file }}"
      name: state

  - name: Install ndppd
    action: apt name=ndppd

  - name: Configure ndppd
    template: src=ndppd.conf.j2 dest={{ ndppd_conf }} owner=root group=root mode=0644

  - name: Enable proxy_ndp for public adapter
    sysctl: name="net.ipv6.conf.{{ public_eth }}.proxy_ndp" value=1 state=present

  - name: Restart ndppd Service
    service: name=ndppd state=restarted
